# This workflow updates Git submodules daily
name: Daily Git Submodule Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are initialized

      - name: Update Git Submodules
        run: |
          git submodule update --remote --recursive
        shell: bash
        
      - name: Download Moodle version file
        run: |
          wget https://raw.githubusercontent.com/moodle/moodle/MOODLE_500_STABLE/version.php -O version.php
        shell: bash
        
      - name: Push updated submodules
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated submodule update"
          git push
        shell: bash
